#!/usr/bin/env bash

# Check if the domain argument is provided
if [[ $# -eq 0 ]]; then
  echo "Please provide a domain name as an argument."
  exit 1
fi

# Assign the domain and subdomain arguments
domain=$1
subdomain=$2

# Function to display subdomain information
display_subdomain_info() {
  local subdomain=$1
  local record_type
  local destination

  # Get the record type and destination using dig command
  record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; print $4}')
  destination=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; print $5}')

  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if subdomain argument is provided
if [[ -z $subdomain ]]; then
  # Display information for default subdomains
  for sub in "www" "lb-01" "web-01" "web-02"; do
    display_subdomain_info "$sub"
  done
else
  # Display information for the specified subdomain
  display_subdomain_info "$subdomain"
fi
