#!/usr/bin/env bash

# Install and configure Nginx

echo "Updating and installing Nginx..."
sudo apt-get update -y -qq && sudo apt-get install nginx -y

echo "Setting up Nginx..."

# Start Nginx service
sudo service nginx start

# Allow Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Configure website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create new index
echo "Hello World!" | sudo dd status=none of=/var/www/html/index.nginx-debian.html

# Restart Nginx
sudo service nginx restart

echo "Completed."
