#!/usr/bin/env bash

# Install and configure Nginx

# Update package lists and install Nginx
sudo apt-get update && sudo apt-get install -y nginx

# Create document root directory and index.html file
sudo mkdir -p /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo echo "Hello World!" > /etc/nginx/html/index.html

# Configure Nginx to listen on port 80 and serve files from the document root
sudo printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Restart Nginx to apply the configuration changes
sudo service nginx restart
