#!/usr/bin/env bash
# Installs and configures HAproxy to load balance traffic between two web servers

# Install HAproxy
apt-get update
apt-get install -y haproxy

# Configure HAproxy
echo 'global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 54.162.233.113:80 check
    server web-02 52.3.253.180:80 check
' > /etc/haproxy/haproxy.cfg

# Restart HAproxy to apply the configuration
systemctl restart haproxy
