#!/usr/bin/env bash
# Configures Nginx to be up and listen on port 80 for all active IPv4 IPs

service nginx status || apt-get update && apt-get install -y nginx
service nginx start
sed -i '/^}$/i listen 80 default_server;' /etc/nginx/sites-available/default
service nginx restart
