#!/usr/bin/env bash
# Ensures Nginx is set up to serve on the standard web port

# Remove existing link to the default site configuration to ensure a clean state
rm /etc/nginx/sites-enabled/default

# Create a new symbolic link for the default Nginx configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
