#!/usr/bin/env bash
# This script displays a list of currently running processes with hierarchy.

# Display the header
printf "%-9s %-5s %-5s %-5s %-5s %-5s %-10s %-5s %-5s %-s\n" "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "START" "TIME"

# Use ps command to get the processes with hierarchy and format the output
ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,comm --forest --sort=-%cpu | sed '1d'
