#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Use pgrep command to find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [[ -n $pid ]]; then
    # If the process is running, use kill command to stop it
    kill "$pid"
    echo "Process $pid stopped"
else
    echo "Process 4-to_infinity_and_beyond is not running"
fi
