#!/usr/bin/env bash
# This script forcefully stops the 4-to_infinity_and_beyond process

# Find the PID of the process
PID=$(pgrep -f '4-to_infinity_and_beyond')

# Check if the PID exists and forcefully kill the process
if [ -n "$PID" ]; then
    kill -9 "$PID"
fi
