#!/usr/bin/env bash
# Script to display username, user id, and home directory path for each user

while IFS=: read -r username _ userid _ _ homedir _; do
    echo "$username:$userid:$homedir"
done < /etc/passwd
