#!/bin/bash
# Display the content of /etc/passwd in a story format using while loop + IFS

# Set the Internal Field Separator to ':'
IFS=":"

# Read /etc/passwd file line by line
while read -r username password uid gid userinfo home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
