#!/bin/bash
# Script to tell the story of each user in /etc/passwd

# Setting the Internal Field Separator (IFS) to colon (:)
# to correctly parse the /etc/passwd file
while IFS=':' read -r username password uid gid info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
