#!/usr/bin/env bash
# Script to group visitors by IP and HTTP status code, and display this data

# Parse log, count occurrences, and sort
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
