#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

count=0 # Initialize counter

until [ $count -ge 10 ]; do
    echo "Best School"
    count=$((count + 1)) # Increment counter
done
