#!/usr/bin/env bash
# This script displays "Best School" 10 times, but says "Hi" on the 9th

count=1 # Initialize counter

while [ $count -le 10 ]; do
    echo "Best School"
    if [ $count -eq 9 ]; then
        echo "Hi"
    fi
    count=$((count + 1)) # Increment counter
done
