#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hour=0 # Initialize hour

while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    minute=1 # Initialize minute for each hour
    while [ $minute -le 59 ]; do
        echo "$minute"
        minute=$((minute + 1)) # Increment minute
    done
    hour=$((hour + 1)) # Increment hour
done
