#!/bin/bash

# Forward traffic from port 8080 to port 80
sudo ufw route allow proto tcp from any to any port 8080 to any port 80

# Reload UFW to apply changes
sudo ufw reload

# Check UFW status
sudo ufw status verbose
