#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080

id -u nginx || useradd -r nginx
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/' /etc/nginx/sites-available/default
service nginx restart
