#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080

id -u nginx || useradd -r nginx
sed -i 's/user www-data;/user nginx;/;s/listen 80;/listen 8080;/;s/listen \[::\]:80;/listen \[::\]:8080;/' /etc/nginx/nginx.conf /etc/nginx/sites-available/default
service nginx restart
