#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080 in 7 lines or less

id -u nginx || useradd -r nginx
sed -i '/^user/s/www-data/nginx/' /etc/nginx/nginx.conf
sed -i '/listen 80 default_server/s/80/8080/' /etc/nginx/sites-available/default
sed -i '/listen \[::\]:80 default_server/s/80/8080/' /etc/nginx/sites-available/default
service nginx restart
