#!/usr/bin/env bash
# This script configures the SSH client to use the private key ~/.ssh/school and disables password authentication
Host *
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
    ChallengeResponseAuthentication no
